[package]
name = "wt_ext_cli"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3
lto = "thin"

[profile.release]
opt-level = 3
lto = true

[dependencies]
clap = {version = "4.1.9", features = ["cargo"]}
indicatif = "0.17.3"
wt_blk = {path = "../wt_blk"}
thiserror = "^1.0"
rayon = "^1.7.0"
open = "^4"

tracing = "^0.1.37"
tracing-subscriber = {version  = "^0.3.16", features = ["tracing-log", "env-filter", "fmt", "std"]}
serde_json = "^1.0"
serde = { version = "^1.0", features = ["serde_derive"] }
serde_bencode = "0.2.3"
anyhow = "1.0.70"
