[package]
name = "wt_ext_cli"
version = "0.0.0" # Unused
edition = "2021"
license = "Apache-2.0"

#[profile.dev]
#opt-level = 3
#lto = "thin"


[profile.release]
opt-level = 3
lto = true
codegen-units = 2

[dependencies]
clap = {version = "4.1.9", features = ["cargo"]}
wt_blk = {git = "https://github.com/Warthunder-Open-Source-Foundation/wt_blk"}
#wt_blk = {path = "../wt_blk"}
thiserror = "^1.0"
rayon = "^1.7.0"
open = "^5"
color-eyre = { version = "^0.6", default-features = false }
time = { version = "0.3.23", default-features = false, features = ["local-offset"]}

tracing = "^0.1.37"
tracing-subscriber = {version  = "^0.3.16", features = ["tracing-log", "env-filter", "fmt", "std"]}
tracing-appender = { version = "0.2.2"}

serde_json = "^1.0"
serde = { version = "^1.0", features = ["serde_derive"] }
const_format = { version = "0.2.31", default-features = false, features = ["fmt"] }
