[package]
name = "wt_ext_cli"
version = "0.2.0"
edition = "2021"

#[profile.dev]
#opt-level = 3
#lto = "thin"


[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 4

[dependencies]
clap = {version = "4.1.9", features = ["cargo"]}
indicatif = "0.17.3"
wt_blk = {git = "https://github.com/Warthunder-Open-Source-Foundation/wt_blk"}
thiserror = "^1.0"
rayon = "^1.7.0"
open = "^4"
tokio = { version = "1.28.1", features = ["rt-multi-thread", "fs", "macros"]}

tracing = "^0.1.37"
tracing-subscriber = {version  = "^0.3.16", features = ["tracing-log", "env-filter", "fmt", "std"]}
serde_json = "^1.0"
serde = { version = "^1.0", features = ["serde_derive"] }
serde_bencode = "0.2.3"
anyhow = "1.0.70"
