[env]
SYSTEM_DEPS_DAV1D_BUILD_INTERNAL = "auto" # Find local dav1d or build it from scratch
SYSTEM_DEPS_DAV1D_LINK = "static" # Force it to be linked statically however

#[build]
#target = "x86_64-unknown-linux-gnu"

[unstable]
#build-std = ["std","alloc","proc_macro","core",]
