name: Nightly release

on:
  push:
    tags:
      - "nv*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install cross for cross installation
      - uses: actions-rs/install@v0.1
        with:
          crate: cross
          version: latest

      - name: Build linux
        run: cargo build --release

      - name: Copy linux executable
        run: mv target/release/wt_ext_cli wt_ext_cli

      # Clean because of https://github.com/cross-rs/cross/issues/724
      - name: Clean cross cache
        run: cross clean

      - name: Build windows
        run: cross build --release --target x86_64-pc-windows-gnu

      - name: Rename windows bin
        run: mv target/x86_64-pc-windows-gnu/release/wt_ext_cli.exe target/x86_64-pc-windows-gnu/release/wt_ext_cli-windows-x86.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            wt_ext_cli
            target/x86_64-pc-windows-gnu/release/wt_ext_cli-windows-x86.exe
            usage_manual.md
            LICENSE