name: Create manual

on:
  release:
    types:
      - created
      - published

jobs:
  build-and-generate-manual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Loads cargo cache
      - uses: actions/cache@v3
        name: Pull Cargo cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build

      - name: Generate Manual
        run: |
          pip install jinja2
          python usage_manual/template_manual.py

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: MANUAL.md
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
