name: Nightly release

on:
  push:
    tags:
      - "nv*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install cross for cross installation
      - uses: actions-rs/install@v0.1
        with:
          crate: cross
          version: latest

      - name: Build linux
        run: cargo build --release

      - name: Build windows
        run: cross build --release --target x86_64-pc-windows-gnu

      - name: Rename linux bin
        run: mv target/release/wt_ext_cli target/release/wt_ext_cli_linux_x86

      - name: Rename linux bin
        run: mv target/release/wt_ext_cli.exe target/release/wt_ext_cli_windows_x86.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            target/release/wt_ext_cli_linux_x86
            target/release/wt_ext_cli_windows_x86.exe
            LICENSE