name: Test build avi2dds feature

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dav1d lib
        run: sudo apt-get update && sudo apt install dav1d=1.3.0-2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dav1d build tools
        run: pip install meson ninja

      # Loads cargo cache
      - uses: actions/cache@v3
        name: Pull Cargo cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --features avif2dds --verbose
      - name: Run tests
        run: cargo test --features avif2dds --verbose